### ISSUE TITLE
The example does not work in Flutter 1.7.8.hotfix3

### ISSUE THREAD

**Issue by Informateur** [michael-cheung-thebus/foreground_service#1]
When using Flutter 1.5.4.hotfix2 everything is fine.

Trying to run on version 1.7.8.hotfix3 (upgrade example or in an empty project) gives the following:

> D/ForegroundServicePlugin(13334): started service, making foreground
> D/ForegroundServicePlugin(13334): started foreground notification, entering service loop
> E/ForegroundServicePlugin(13334): unexpected error while handling intent: Methods marked with @UiThread must be executed on the main thread. Current thread: IntentService[org.thebus.ForegroundServicePlugin]

**Comment by SGuzel** [comment]
unexpected error while handling intent: Methods marked with @UiThread must be executed on the main thread. Current thread: IntentService[org.thebus.ForegroundServicePlugin] 

I also have the some output.

**Comment by michael-cheung-thebus** [comment]
Version 0.2.1 should fix this issue, please confirm.

**Comment by Informateur** [comment]
It works well! Grace
