### ISSUE TITLE
Not updating notification

### ISSUE THREAD

**Issue by luisestudioalfa** [michael-cheung-thebus/foreground_service#13]
Hello,
i have followed the installation and the example.

The notification is created but it is not updated.

on the output shows:
W/lfa.demo(11343): JNI critical lock held for 46.678ms on Thread[4,tid=11455,Runnable,Thread*=0xe716b600,peer=0x13040200,"IntentService[org.thebus.ForegroundServicePlugin]"]
D/QueuedWork(11343): waited: [<1: 0, <2: 1015, <4: 8, <8: 1, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]

Any idea?

Can i use the foreground service to call a geolocation service to know the position of the user? or is there a better alternative?

Thank you in advance.

**Comment by Sandeep-GitAcc** [comment]
Hey, 
Is this issue resolved? 
I am following the example and my code is almost same as example code. 
I receive notification the first time I start debugging my app. But after that I receive no notification. I had set the internal of 10 sec (setServiceIntervalSeconds) and had set ForegroundService.setContinueRunningAfterAppKilled(true).
