### ISSUE TITLE
my function don't executed

### ISSUE THREAD

**Issue by walide67** [michael-cheung-thebus/foreground_service#16]
o want the to use this plugin to run location tracking service but the function does not run 
the function code :

```
Future<void> foregroundServiceFunction() async {
  final Location _locationService = Location();
  final PermissionStatus _status = await _locationService.hasPermission();
 if(_status == PermissionStatus.granted){
   final LocationData location = await _locationService.getLocation();
    await ForegroundService.notification
          .setTitle("${DateTime.now()} | lat : ${location.latitude}");
      await ForegroundService.notification
          .setText("${DateTime.now()} | Long : ${location.longitude}");
 }else{
   await ForegroundService.notification
          .setTitle("${DateTime.now()} | Permission Denied");
 }
```
but when i test with the example function it's work fine
please need your help

**Comment by Drolegc** [comment]
What errors did it display?

**Comment by priyeshdabre** [comment]
Yes, Even I am getting the same issue. Even in Example the forgroundsServiceFunction doesn't work.

**Comment by walide67** [comment]
> What errors did it display?

i change location plugin with geolocator and get this exception : 

> Exception has occurred.
> PlatformException (PlatformException(error, Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference, null))

**Comment by Sandeep-GitAcc** [comment]
Hey all,

I am receiving the following error:
```
Error -32601 received from application: Method not found
method not available: ext.flutter.platformOverride
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.setPubRootDirectories
Error -32601 received from application: Method not found
method not available: ext.flutter.inspector.isWidgetCreationTracked
D/ForegroundServicePlugin(23264): started service, making foreground
D/ForegroundServicePlugin(23264): started foreground notification, entering service loop
```

This was thrown even with example. I am consuming v1.1.5.

Following output is logged when service is running 
```
D/QueuedWork(21061): waited: [<1: 0, <2: 77103, <4: 585, <8: 108, <16: 23, <32: 5, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
```

Is there any configuration missing which caused this or this is a bug?

**Comment by walide67** [comment]
> Hey all,
> 
> I am receiving the following error:
> 
> ```
> Error -32601 received from application: Method not found
> method not available: ext.flutter.platformOverride
> Error -32601 received from application: Method not found
> Error -32601 received from application: Method not found
> method not available: ext.flutter.inspector.setPubRootDirectories
> Error -32601 received from application: Method not found
> method not available: ext.flutter.inspector.isWidgetCreationTracked
> D/ForegroundServicePlugin(23264): started service, making foreground
> D/ForegroundServicePlugin(23264): started foreground notification, entering service loop
> ```
> 
> This was thrown even with example. I am consuming v1.1.5.
> 
> Following output is logged when service is running
> 
> ```
> D/QueuedWork(21061): waited: [<1: 0, <2: 77103, <4: 585, <8: 108, <16: 23, <32: 5, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
> ```
> 
> Is there any configuration missing which caused this or this is a bug?

The 2 functions must be static or top-level

**Comment by walide67** [comment]
My issue was be solved .. The problem was in geolocator and now it's fixed

**Comment by michael-cheung-thebus** [comment]
@priyeshdabre @Sandeep-GitAcc Please open separate issues with more details about your code/what you see.

Closing this issue per comment from author.

**Comment by Sandeep-GitAcc** [comment]
> 
> 
> > Hey all,
> > I am receiving the following error:
> > ```
> > Error -32601 received from application: Method not found
> > method not available: ext.flutter.platformOverride
> > Error -32601 received from application: Method not found
> > Error -32601 received from application: Method not found
> > method not available: ext.flutter.inspector.setPubRootDirectories
> > Error -32601 received from application: Method not found
> > method not available: ext.flutter.inspector.isWidgetCreationTracked
> > D/ForegroundServicePlugin(23264): started service, making foreground
> > D/ForegroundServicePlugin(23264): started foreground notification, entering service loop
> > ```
> > 
> > 
> > This was thrown even with example. I am consuming v1.1.5.
> > Following output is logged when service is running
> > ```
> > D/QueuedWork(21061): waited: [<1: 0, <2: 77103, <4: 585, <8: 108, <16: 23, <32: 5, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
> > ```
> > 
> > 
> > Is there any configuration missing which caused this or this is a bug?
> 
> The 2 functions must be static or top-level

@priyeshdabre my functions are top level function defined in a separate file. 
@michael-cheung-thebus I will raise the issue to understand what those logs are and how I can handle them. For the time being, except on first launch, the service seems to be working. Will try to debug this scenario.

**Comment by spalenzuela** [comment]
> My issue was be solved .. The problem was in geolocator and now it's fixed

How did you solve it?
