### ISSUE TITLE
Could not register plugin callback

### ISSUE THREAD

**Issue by Informateur** [michael-cheung-thebus/foreground_service#2]
When creating a new project and performing steps 1-3, OverrideApplication.kt is located in the folder with MainActivity.kt, package default com.flutter_app. The icon near the clock appears. The terminal writes:

> E/ForegroundServicePlugin(17503): Could not register plugin callback.  Did you call ForegroundServicePlugin.setPluginRegistrantCallback?
> D/ForegroundServicePlugin(17503): started service, making foreground
> D/ForegroundServicePlugin(17503): started foreground notification, entering service loop

How to perform step 1 correctly? In the example, the tips did not find.

**Comment by OliverWangWei** [comment]
@Informateur I'm in the same situation.

**Comment by michael-cheung-thebus** [comment]
The message indicates that the line
`ForegroundServicePlugin.setPluginRegistrantCallback(this)`

in Step 1 is not being called.

This could happen either if the line is not present, or if the manifest doesn't change the application to OverrideApplication instead of the default io.flutter.app.FlutterApplication. (<application android:name=".OverrideApplication"> in Step 2).

**Comment by Informateur** [comment]
It seems this renaming is not critical for the project. I was afraid that both the package and the label refers to my names.
It works well. Thank you very much!

P.S.
I was able to connect patients to monitor their health 24/7. That's cool!

**Comment by Sandeep-GitAcc** [comment]
Hey @michael-cheung-thebus,
I am following the example mentioned in the repo with a few additional properties enabled. But I am getting the same error when I start debugging.

`
initiateBackgroundService() async {
  if (!await ForegroundService.foregroundServiceIsStarted()) {
    await ForegroundService.setServiceIntervalSeconds(SERVICE_INTERVAL);
    ForegroundService.notification.startEditMode();
    await ForegroundService.notification.setTitle(NOTIFICATION_TITLE);
    await ForegroundService.notification.setText(NOTIFICATION_TEXT);
    await ForegroundService.notification.finishEditMode();
    await ForegroundService.startForegroundService(foregroundServiceFunction);
    await ForegroundService.getWakeLock();
    await ForegroundService.setContinueRunningAfterAppKilled(true);
  }
}

Future<void> foregroundServiceFunction() async {
  ForegroundService.notification.setText("The time was: ${DateTime.now()}");
}
`

When I start debugging session and this foreground_service is run, a notification is received. No other notification is received after that. But ForegroundService.setContinueRunningAferAppKilled is set to true. 
 
**Doubt**:  There is a reference to step 1-3. I couldn't find any step suggesting changing name in manifest file or the referred step. Could you please attach the same in readme file or direct me the guide.

Please help.
