### ISSUE TITLE
Open the app from the foreground

### ISSUE THREAD

**Issue by ezequielvictor** [michael-cheung-thebus/foreground_service#22]
I'm trying to open the app through the foreground, but I can't access the context to call in any way, any ideas?

**Comment by michael-cheung-thebus** [comment]
It's not too clear to me what you're asking.  Can you describe with more detail/step by step the intended workflow?

**Comment by Lootwig** [comment]
Is it possible to open the app by tapping on the notification? Maybe that's what OP wanted to know as well.

**Comment by Kundan-Android** [comment]
@michael-cheung-thebus  Is it possible open by tapping on the notification?
@Lootwig @ezequielvictor did you get any solution for this?
