### ISSUE TITLE
How to customize the interface for notifications

### ISSUE THREAD

**Issue by 20140103** [michael-cheung-thebus/foreground_service#24]

**Comment by michael-cheung-thebus** [comment]
The only things that can be customized for the notification associated with the foreground service created via this plugin are:

- icon
  Replacing the icon specified in the README will change the icon.
  Unfortunately that of course means this can't be done programatically/dynamically.

- title
  Using ForegroundService.notification.setTitle()

- text
  Using ForegroundService.notification.setText

- priority
  Using ForegroundService.notification.setPriority


I could have sworn these were exposed in the docs, but I guess not.  Will have to look at that.

At this time there are no other things that can be customized for the notification, and no plans to add any.  It's really less of a notification and more of a status banner.

For actual/richer notifications, I would suggest looking at/using [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications).
