### ISSUE TITLE
How can stop foreground service when app its killed

### ISSUE THREAD

**Issue by Drolegc** [michael-cheung-thebus/foreground_service#26]
I have an app that use this plugin, now im trying to figure it out, how to stop the service when the user kills the app by swiping it from recent apps.

Like this example:
https://stackoverflow.com/questions/19568315/how-to-handle-code-when-app-is-killed-by-swiping-in-android

**Comment by michael-cheung-thebus** [comment]
Try

`await ForegroundService.setContinueRunningAfterAppKilled(false);`
