### ISSUE TITLE
Send data between foreground function and main app

### ISSUE THREAD

**Issue by sd-timaru** [michael-cheung-thebus/foreground_service#3]
Hi!
It is possible to send data from the foreground service to the main app?
For example,  how can i update a counter on the main UI every time the foregroundServiceFunction()  is called?
Thanks!

**Comment by michael-cheung-thebus** [comment]
@sd-timaru The point of this plugin is to be able to callback to a Dart function during foreground service execution - in other words, get the Android functionality of a foreground service without needing to know a lick of Kotlin/Java/etc.

If you want have data on both the Android side and Dart side, and communicate between the two, you're going to want to look into [method channels](https://flutter.dev/docs/development/platform-integration/platform-channels).

Using a Dart function, you would update the Flutter UI just like you would with other top-level Dart functions.

**Comment by Nico04** [comment]
Hi, 
I've managed to makes the service work quite quickly, but now I struggle how to return and use values from the service callback and the main app. As you said, all function content must be self contained, so how am I supposed to communicate with main dart code ?
I've tried calling external code but it doesn't work, and as you said in the code, static vars are different so no exchange is possible.

And how can I update the notification from the service callback ?
