### ISSUE TITLE
Can't use other plugin inside foregroundservice. I want to use geolocator plugin to fetch location

### ISSUE THREAD

**Issue by hrishiksh** [michael-cheung-thebus/foreground_service#42]
I want to track a user location continuously by combining foreground service and geolocator plugin. But It is not working. The geolocator plugin isn't running at all. please guide me what to do.

**Comment by hrishiksh** [comment]
It is working now. My fault. Please ignore.

**Comment by Marcoslima016** [comment]
Hi @hrishiksh , I'm not being able to access plugins from within the foreground service (running in background, app terminated) . Could you explain to me how you did it? Thanks.
