### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.

### ISSUE THREAD

**Issue by GianfrancoMS** [michael-cheung-thebus/foreground_service#5]
When I try to call the foreground service, the following exception is thrown:

```
D/ForegroundServicePlugin( 9113): started service, making foreground
D/ForegroundServicePlugin( 9113): started foreground notification, entering service loop
E/flutter ( 9113): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'toRawHandle' was called on null.
E/flutter ( 9113): Receiver: null
E/flutter ( 9113): Tried calling: toRawHandle()
E/flutter ( 9113): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 9113): #1      ForegroundService.setServiceFunction (package:foreground_service/foreground_service.dart:53:60)
E/flutter ( 9113): <asynchronous suspension>
E/flutter ( 9113): #2      ForegroundService.startForegroundService (package:foreground_service/foreground_service.dart:33:7)
E/flutter ( 9113): <asynchronous suspension>
E/flutter ( 9113): #3      ForegroundServiceProvider.initGeoLocation (package:tappers/foreground_service.dart:28:31)
E/flutter ( 9113): <asynchronous suspension>
E/flutter ( 9113): #4      _ShippingScheduleWidget.initGeoLocation (package:tappers/features/shipper/presentation/views/shipping_schedule_widget.dart:123:25)
E/flutter ( 9113): <asynchronous suspension>
E/flutter ( 9113): #5      _ShippingScheduleWidget.build (package:tappers/features/shipper/presentation/views/shipping_schedule_widget.dart:157:9)
E/flutter ( 9113): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter ( 9113): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter ( 9113): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter ( 9113): #9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter ( 9113): #10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter ( 9113): #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter ( 9113): #12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter ( 9113): #13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter ( 9113): #14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter ( 9113): #15     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 9113): #16     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 9113): #17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 9113): #18     _invoke (dart:ui/hooks.dart:249:10)
E/flutter ( 9113): #19     _drawFrame (dart:ui/hooks.dart:207:3)
```

flutter doctor -v

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Versionn 10.0.17763.737], locale es-419)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter
    • Framework revision 2d2a1ffec9 (11 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by LuizGX** [comment]
This is the line: 
await ForegroundService.startForegroundService(foregroundServiceFunction)

When i tried to call it like:
await ForegroundService.startForegroundService( () {
    debugPrint("This is the time : ${DateTime.now()}");
});
I had the same issue as you, it seems like if you don't pass a function like the first example the whole thing resolves as null and so you can't access like you wanted to.

**Comment by mustafal** [comment]
you have to just add `()` behind the method name like this `await ForegroundService.startForegroundService(foregroundServiceFunction())`

**Comment by mustafal** [comment]
I had one issue in the plugin. I got the following error because my method returns the `Future<dynamic>` and the plugin needs `Function`.

`Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'Function'`,
Please Guide me on how I can solve this issue?
Thanks in advance.

**Comment by michael-cheung-thebus** [comment]
Yes, a function needs to be passed to startForegroundService - there didn't seem to be a use-case for a foreground service that doesn't do anything.

The function also needs to be non-anonymous because the foreground service needs a handle to use for the callback, and the function used to get the handle (PluginUtilities.getCallbackHandle) is not able to return a handle for anonymous functions.

If you're aware of a way to get handles that also works for anonymous functions, LMK - I personally don't see much use for it, but if others might then why not, eh?

@mustafal startForegroundService expects the actual function that the service should execute - not the result of a function.  If the function to execute is called foregroundServiceFunction, then startForegroundService(foregroundServiceFunction) is the correct call.

**Comment by mustafal** [comment]
@michael-cheung-thebus  Thanks a lot for the reply.

But what if my function returns something and I want a result from that, and let me be very honest I am using an MQTT protocol for make a request in the Server and get a response from that in the foreground(the app is not visible in the stack). Here is My code for passing some information in MQTT and get updates.

`     mqttConnect() async {
       client = MqttClient(serverCtrl.text.length != null ? serverCtrl.text : "", Uuid().v1());

      client.logging(on: true);
      client.keepAlivePeriod = 60;
      client.onDisconnected = onDisconnected;
      client.onConnected = onConnected;
      client.onSubscribed = onSubscribed;
      client.pongCallback = pong;

      try {
        await client.connect(userNameCtrl.text != null ? userNameCtrl.text : "",
            passwordCtrl.text != null ? passwordCtrl.text : "");
      } on Exception catch (e) {
        client.disconnect();
      }
      if (client.connectionStatus.state != MqttConnectionState.connected) {
        client.disconnect();
      }
      String topic =
          topicCtrl.text != null ? topicCtrl.text : ""; // Not a wildcard topic
      client.subscribe(topic, MqttQos.atMostOnce);
      final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
      builder.addString(messageCtrl.text != null ? messageCtrl.text : "");
      client.publishMessage(topic, MqttQos.exactlyOnce, builder.payload);

      /* Receive the Updates from the mqtt server */

      client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
        final MqttPublishMessage recMess = c[0].payload;
        final String pt =
            MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

        setState(() {
          message =
              "Change notification:: topic is <${c[0].topic}>, payload is <-- $pt -->";
        });
      });

      await MqttUtilities.asyncSleep(120);

      message = "Unsubscribing";
      client.unsubscribe(topic);

      await MqttUtilities.asyncSleep(2);
      message = "Disconnecting";
      client.disconnect();
      message = "Disconnected";
    }
`

I am calling this function on the press of the button.

`    void startFGS() async {
      await ForegroundService.setServiceIntervalSeconds(5);
  
      //necessity of editMode is dubious (see function comments)
      await ForegroundService.notification.startEditMode();
  
      await ForegroundService.notification.setTitle("Flutter MQTT Example");
      await ForegroundService.notification.setText("Flutter MQTT Example");
  
      await ForegroundService.notification.finishEditMode();
      await ForegroundService.startForegroundService(mqttConnect());
      await ForegroundService.getWakeLock();
    }
`
and I got this error.

`Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'Function'`

**So is there any way to update my `mqttConnect()` function so I can pass that function in my `startForgroundService()` method?**.

Please help me with this.
Thank you in advance.

**Comment by michael-cheung-thebus** [comment]
What happens when you leave out the parentheses, i.e.
`await ForegroundService.startForegroundService(mqttConnect);`
?

I don't see a return statement in the mqttConnect function - what does it return?
An easy way to get return values is to just use a wrapper - i.e.

```
void fgsFunction() async{
 var connectResult = await mqttConnect();
 //do something with connectResult
}

await ForegroundService.startForegroundService(fgsFunction);
```

Also, I'm not sure using a foreground service is really what you want/need - I would guess that a regular service/job or a timer might fit your application better.

**Comment by mustafal** [comment]
I want that my app is running in the background. but the thing is that I want to make some network calls in the background and on the bases of the result I want to make the MQTT request.
So, can you please suggest me what I have to do I have to use background service or foreground service?

**Comment by michael-cheung-thebus** [comment]
@mustafal This guide was written to help you answer precisely that question: https://developer.android.com/guide/background

**Comment by mustafal** [comment]
Ok, Thanks!! @michael-cheung-thebus
