### ISSUE TITLE
Migrate to Flutter 1.12

### ISSUE THREAD

**Issue by Informateur** [michael-cheung-thebus/foreground_service#8]
In flutter 1.12 `GeneratedPluginRegistrant.registerWith(p0)` method returns an error:
> Type mismatch: inferred type is PluginRegistry? but FlutterEngine was expected

How can this conflict be resolved in the new version?

**Comment by Informateur** [comment]
Replaced by:
`override fun registerWith(p0: PluginRegistry) {ForegroundServicePlugin.registerWith(p0.registrarFor("org.thebus.foreground_service.ForegroundServicePlugin"))}`

**Comment by michael-cheung-thebus** [comment]
v1.1.0 has been published, give it a shot.

After the Flutter 1.12 changes, you shouldn't need to do anything on the Android side besides have the notification icon - in other words, you can delete the custom application class etc. etc.

**Comment by Informateur** [comment]
I knew there was an elegant way. Thanks a lot!
