### ISSUE TITLE
[Feature Request] 2 Ways communication

### ISSUE THREAD

**Issue by Nico04** [michael-cheung-thebus/foreground_service#9]
[Like Dart Isolate natively do](https://medium.com/@lelandzach/dart-isolate-2-way-communication-89e75d973f34), I think it's very important that the foreground service has a way of communicate with the main Flutter UI. At least just a way to handle errors, results, call callbacks, etc.

For now as the service callback is run in a isolate without any ReceivePort, there are no way to do that, so this service can only do very basic or isolated tasks.

**Comment by taojoe** [comment]
@Nico04  you can use IsolateNameServer in the dart:ui.

**Comment by michael-cheung-thebus** [comment]
Version 1.2.0 allows hooking up of send/receive ports between service/main via ForegroundService.setupIsolateCommunication and ForegroundService.sendToPort.
